dataset_name: "timit"

model_name: "AST"

windowing:
  fs:  16000
  cw_len:  200
  cw_shift:  40
  resample: 16000

optimization:  
  lr:  0.0001
  batch_size: 128
  N_epochs:  100
  N_batches:  1300  #1300*(256/64)
  N_eval_epoch: 8
  seed:  479